jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
#        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: jellyfin.local
          paths:
            - path: /
              pathType: Prefix
#      tls:
#        - secretName: jellyfin-tls-certificate
#          hosts:
#            - *host
