# TODO create user and access token
# users:
#   - name: renovate
#     fullName: Renovate
#     email: bot@renovateapp.com
#     tokenSecretRef: renovate-secret # ???
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/kre80r/homelab
      mirror: false
    # TODO create webhook (use a global one?)
    # webhooks:
    #   - http://gitea-webhook.tekton-pipelines:3000
  - name: blog
    owner: kre80r
    migrate:
      source: https://github.com/kre80r/blog
      mirror: true
  - name: backstage
    owner: kre80r
    migrate:
      source: https://github.com/kre80r/backstage
      mirror: true
