paperless:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
      hosts:
        - host: paperless.local
          paths:
            - path: /
              pathType: Prefix
  env: 
    PAPERLESS_REDIS: redis://paperless-redis-master:6379
    PAPERLESS_ADMIN_USER: admin
    PAPERLESS_ADMIN_PASSWORD: admin
  postgresql:
    enabled: true
  redis:
    enabled: true
    auth:
      enabled: false
