paperless:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/appName: Paperless
        hajimari.io/icon: file-document
      hosts:
        - host: paperless.local
          paths:
            - path: /
              pathType: Prefix
  postgresql:
    enabled: true
