gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
#      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: git.local
        paths:
          - path: /
            pathType: Prefix
#    tls:
#      - secretName: gitea-tls-certificate
#        hosts:
#          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: http://git.local
  persistence:
    storageClass: local-path
  postgresql:
    persistence:
      storageClass: local-path
